from crewai import Task
from pydantic import BaseModel, Field
from typing import List
import os
from crewai_agents.agents.a2_search_engine_agent import search_engine_agent
from crewai_agents.config import output_dir

class SignleSearchResult(BaseModel):
    title: str
    url: str 
    content: str
    score: float
    search_query: str

class AllSearchResults(BaseModel):
    results: List[SignleSearchResult]

search_engine_task = Task(
    description="\n".join([
        "The task is to search for products based on the suggested search queries.",
    ]),
    expected_output="A JSON object containing the search results.",
    output_json=AllSearchResults,
    output_file=os.path.join(output_dir, "step_2_search_results.json"),
    agent=search_engine_agent,
)
#  {queries} → pulls the list generated by Task #1.
# after Task #2 completes, the context will contain a Python list under the key results.